# Evaluating the best model on out-of-sample test data
# Keaton Wilson
# keatonwilson@me.com
# 2019-11-25

require(raster)
require(tidyverse)
require(dismo)

#'  Evaluating final model on spatially-explicit test data
#' 
#' \code{evaluate_models} uses the \code{\link[dismo]{evaluate}} function to 
#' evaluate a final model on the spatially-explicit test data generated by 
#' \code{\link{run_block_cv}}. 
#' 
#' @param test_data the test data generated from the 
#' \code{\link{train_test_split}} function (should include background data). 
#' 
#' @param model the final model being tested, typically generated by the 
#' \code{\link{best_mod}} function. 
#' 
#' @param env_raster the environmental raster pertaining to a particular 
#' time-period and data set being tested. Using the cropped rasters 
#' (and not full) rasters is important here. 
#'
#' @return a \code{link[dismo]} evaluate object.   
#'
#' @examples

evaluate_models = function(test_data, model, env_raster) {
  test_data_occ = test_data %>%
    filter(Species == 1) %>%
    dplyr::select(longitude, latitude)
  
  bg_data = test_data %>%
    filter(Species == 0) %>%
    dplyr::select(longitude, latitude)
  
  ev = evaluate(test_data_occ, a = bg_data, model = model, x = env_raster, type = 'cloglog')
  return(ev)
}
