# Building full final model on all of the data
# Keaton Wilson
# keatonwilson@me.com
# 2019-11-25

# packages
require(raster)
require(ENMeval)
require(maxnet)
source("./script/functions/make_args.R")


#' full_model - function to build out full model on all data after 
#' hyperparameter tuning
#' 
#' The full model here refers to the final built for mapping and analysis, after
#'  model selection, with the full complement of data (training + test). 
#'
#' @param models_obj an ENMeval models object returned from the 
#' \code{\link{model_func}} function
#' 
#' @param best_model_index the index of the best model from the ENMeval model 
#' object, generated by the \code{\link{best_mod}} function
#' 
#' @param full_data the full set of data (training + test) used to build the 
#' final model on  
#' 
#' @param env_raster the appropriate env_raster for a given time period  
#'
#' @return a model object from maxnet
#' @export
#'
#' @examples
full_model = function(models_obj, best_model_index, full_data = NULL, 
                      env_raster) {
  
  auc_mod = models_obj@results[best_model_index,]
  FC_best = tolower(as.character(auc_mod$fc[1]))
  rm_best = as.numeric(auc_mod$rm)
  
  
  # maxent.args = make_args(RMvalues = rm_best, fc = FC_best)
  # 
  # re calculating environmental raster
  
  
  # full_mod = maxent(env_raster, as.matrix(full_data[,1:2]), args = maxent.args[[1]])
  full_mod = try(maxnet(p = full_data$Species, data = full_data[,1:19],
                        maxnet.formula(full_data$Species, 
                                       full_data[,1:19], 
                                       classes = FC_best), 
                        regmult = rm_best))
  if (class(full_mod) == "try-error") {
    cat("Caught an error running maxnet, trying maxent")
    
    FC_best = as.character(auc_mod$fc[1])
    maxent.args = make_args(RMvalues = rm_best, fc = FC_best)[[1]]
    
    
    full_mod = try(dismo::maxent(p = full_data$Species, x = full_data[,1:19],
                                 args = maxent.args))  
  }
  
  return(full_mod)
  
  
  
}  
