# Function to split a multi-species occurence data frame into species-specific 
# .rds files 
# Keaton Wilson
# keatonwilson@me.com
# 2020-01-15 
require(stringr)
require(tidyverse)


#' split_multi_occ 
#' Splits a multi-species dataframe of occurence data into dataframes for each 
#' species into a new directory. Multi-species dfs are typically generated by 
#' scripts from the pulling_organizing_data folder, but we need separate 
#' dataframes to run multiple species in parallel
#'
#' @param multi_species_df the multi-species dataframe to be split
#'
#' @return nothing, but writes the individual dataframes as .rds files to a new 
#' directory at the top level of organization of the project called split_data
#' @export
#'
#' @examples
split_multi_occ = function(multi_species_df, year_split){
# QC to make sure we have enough records for each species
data_summary = multi_species_df %>%
  mutate(year = lubridate::year(date)) %>%
  filter(!is.na(year)) %>%
  mutate(time_frame = ifelse(year > year_split, "T1", "T2")) %>%
  group_by(name, time_frame) %>%
  summarize(n = n()) %>%
  print(n = 50)

invisible(readline(prompt="Does this data summary look reasonable?
  Check to make sure you have enough data for each species to continue.
  Press [enter] to continue"))

#making a new directory
dir.create('./data/split_data')

#pulling out src_name
df = multi_species_df %>%
  select(-src_name)
# split multi-species dataframe into a list
butt_list = split(df, f = df$name)

#Writing each component of the list out to rds file
files = c()
for(i in 1:length(names(butt_list))) {
  files[i] = paste0("./data/split_data/", 
                    str_replace(str_to_lower(names(butt_list)[i]), " ", "_"), 
                    ".rds")
}

for(j in 1:length(names(butt_list))){
  saveRDS(butt_list[[j]], files[j])
}

}