---
title: "script_readme"
author: "Keaton Wilson"
date: "5/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scripts Overview  
The script folder contains the programmatic pieces of this project. Major 
components include:  
1. *pulling_organizing_data* - scripts for grabbing occurence data from GBIF and 
iNaturalist, as well as obtaining and manipulating environmental rasters.  
2. *functions* - The bulk of the code that is ultimately sourced by 
`build_sdm()` and the *master.R* script to initiate the entire workflow of 
building and testing temporally explicit SDMs.  
3. *pbs_scripts* - .pbs scheduler scripts for running analyses on the UArizona 
HPC.  
4. *analysis_mapping* - scripts and workflows related to post-model analysis and
visualization.  
5. *monte_carlo_methods* - a preliminary set of scripts that explore some monte 
carlo methodology for repeated downsampling of the more current time period to 
match the number of records of the older time period.  
6. *utils* - a directory for general purpose scripts - currently only contains 
the `eval_plots()` function which generates visualization of hyperparameter 
tuning for a given set of models generated by `build_sdm()`.   
